name: log_file_writer
description: "Prints logs to a log file."
version: 1.0.0
homepage: null

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  date_format: ^2.0.7
  flutter:
    sdk: flutter
  flutter_email_sender: ^7.0.0
  logging: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter: null
