name: log_file_writer
description: "Prints logs to a log file."
version: 0.0.6
homepage: null

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  date_format: ^2.0.7
  flutter:
    sdk: flutter
  flutter_email_sender: ^6.0.2
  logging: ^1.2.0
  path: ^1.9.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter: null
